version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: event-db
    restart: always
    environment:
      POSTGRES_DB: event_booking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "8002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: